management:
  endpoints:
    web:
      exposure:
        include: '*'
  info:
    env:
      enabled: true

info:
  application:
    name: woco-back
    description: REST API
    author: ----------------
    version: '@project.version@'
spring:
  profiles:
    active: prod